# Generated by Django 5.1.1 on 2024-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_image_phone_lte_exists_phone_name_phone_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
    ]
